#!/bin/bash
# update youtube-dl , 20211115 now yt-dlp

[ -n "$(which xterm)" ] && export _TERM=xterm || export _TERM=rxvt

in_term () {
echo "Updating youtube-dl . . ."
echo "youtube-dl is not developed anymore"
echo "this will install or update yt-dlp and create symlink youtube-dl"
if [ -x /usr/local/bin/youtube-dl -a ! -L /usr/local/bin/youtube-dl ]; then
echo "existng youtube-dl will be renamed to youtube-dl.bak (if not already)"

read -p "Continue? (Enter=yes) (Y/n)?" choice

case "$choice" in 
  y|Y|"")
#curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
#chmod a+rx /usr/local/bin/youtube-dl
  if [ ! -x /usr/local/bin/yt-dlp ]; then
  curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
  chmod a+rx /usr/local/bin/yt-dlp
  else
  yt-dlp -U
  fi

if [ $(readlink -f /usr/local/bin/youtube-dl) != /usr/local/bin/yt-dlp ]; then
mv -f /usr/local/bin/youtube-dl /usr/local/bin/youtube-dl.bak
ln -sf /usr/local/bin/yt-dlp /usr/local/bin/youtube-dl
fi
echo "youtube-dl (yt-dlp) version is:"
yt-dlp --version
sleep 6
;;
  n|N)
echo "Exiting..."
sleep 3
exit 0
;;
*)
echo -e "\e[0;31mNot a valid choice, exiting....\033[0m"
sleep 3
exit 0
;;
esac
else
  if [ ! -x /usr/local/bin/yt-dlp ]; then
  curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
  chmod a+rx /usr/local/bin/yt-dlp
[ ! -L /usr/local/bin/youtube-dl ] && ln -sf /usr/local/bin/yt-dlp /usr/local/bin/youtube-dl && echo "installed yt-dlp and created symlink youtube-dl"
  echo "youtube-dl (yt-dlp) version is:"
  yt-dlp --version
  sleep 6
  else
  yt-dlp -U
  ln -sf /usr/local/bin/yt-dlp /usr/local/bin/youtube-dl
[ ! -L /usr/local/bin/youtube-dl ] && ln -sf /usr/local/bin/yt-dlp /usr/local/bin/youtube-dl && echo "created symlink youtube-dl"
  echo "youtube-dl (yt-dlp) version is:"
  yt-dlp --version
  sleep 6
  fi
fi
}
export -f in_term

$_TERM -rv -geometry 80x10 -e bash -c in_term
